version: '3'

services:
    db:
        image: "postgres:12.1"
        container_name: newtbase-db
        restart: unless-stopped
        ports:
            - 5432
        env_file:
            - ./.env
        volumes:
            - pg-newtbase-data:/var/lib/postgresql/data
            - ./db:/newtbase-data
        networks:
            - newtbase-net

    nginx:
        image: nginx:latest
        restart: always
        container_name: newtbase-nginx
        ports:
            - 8001:80
        depends_on:
            - web
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - web-static:/app/static_root
        networks:
            - newtbase-net

    web:
        build: .
        container_name: newtbase-web
        restart: always
        env_file:
            - ./.env
        ports:
            - "8001"
        command: /usr/local/bin/gunicorn newtbase.wsgi -w 2 -b :8001
        volumes:
            - .:/app
            - web-static:/app/static_root
        depends_on:
          - db
        networks:
            - newtbase-net

volumes:
  web-static:
  pg-newtbase-data:

networks:
  newtbase-net:
