version: '3'

services:
    db:
        image: "postgres:12.1"
        container_name: newtbase-db
        restart: unless-stopped
        ports:
            - 5432
        env_file:
            - ./.env
        volumes:
            - pg-newtbase-data:/var/lib/postgresql/data
            - ./db:/newtbase-data
        networks:
            - newtbase-net

    web:
        build: .
        container_name: newtbase-web
        restart: always
        env_file:
            - ./.env
        ports:
            - "8001:8001"
        command: /usr/local/bin/python manage.py runserver 0.0.0.0:8001
        volumes:
            - .:/app
            - web-static:/app/static_root
#            - ./blastplus:/app/blastplus
        depends_on:
          - db
        networks:
            - newtbase-net

volumes:
  web-static:
  pg-newtbase-data:

networks:
  newtbase-net:
